name: Bug report
description: Report a bug or unexpected behavior
body:
  - type: markdown
    attributes:
      value: |
        This form is **only for bug reports**.

        Please do not use this form for questions or feature requests.
        Make sure **all required information** is provided so the issue can be properly analyzed.

        ⚠️ **IMPORTANT**
        Meaningful support is only possible if all required information is provided,
        especially **diagnostics data** and **log files**.
        Issues without this information may be closed without further notice.

        Please read all sections carefully and fill out the form completely.

  - type: checkboxes
    attributes:
      label: Confirmation
      options:
        - label: I have checked the **Good first issues** list to ensure this problem has not already been reported or resolved.
          required: true
        - label: I have read the **README** and followed all relevant instructions.
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: Problem description
      description: |
        Please describe the issue as clearly as possible and answer the following questions:

        1. What is happening?
        2. When and how does it occur?
        3. What did you expect to happen?
        4. What have you already tried?

        **Do NOT include logs here.** Screenshots are welcome.

  - type: markdown
    attributes:
      value: |
        ## Environment

  - type: input
    validations:
      required: true
    attributes:
      label: Affected integration version
      placeholder: x.y.z
      description: |
        Enter the version of the integration where the issue occurs.

  - type: input
    attributes:
      label: Last working integration version
      placeholder: x.y.z
      description: |
        If known, otherwise leave blank.

  - type: markdown
    attributes:
      value: |
        ## Details

  - type: textarea
    attributes:
      label: Diagnostics file (required)
      placeholder: "Drag and drop the diagnostics .json file here."
      description: |
        ⚠️ **IMPORTANT**
        Upload the diagnostics file **only as a file** using drag and drop.

        Do NOT paste logs or text content here.

        Skip this field only if the issue occurs during initial setup.

  - type: textarea
    attributes:
      label: Log file (required)
      placeholder: "Drag and drop the log file here."
      description: |
        Please upload the relevant log file.
        DEBUG-level logs are strongly recommended.

        Make sure the log covers the time when the issue occurred
        and does not contain sensitive information.
