# custom_components/hcu_integration/services.yaml
play_sound:
  name: Play Sound
  description: Plays a specific sound file on a compatible Homematic IP device (e.g., Siren or Doorbell).
  target:
    entity:
      - integration: hcu_integration
        domain: light # Or any domain where a compatible entity might appear
  fields:
    sound_file:
      name: Sound File
      description: "The name of the sound file to play, as defined in the HCU API documentation (e.g., SOUNDFILE_001, RANDOM_SOUNDFILE)."
      example: "SOUNDFILE_001"
      required: true
      selector:
        text:
    volume:
      name: Volume
      description: "The playback volume, from 0.0 (silent) to 1.0 (full)."
      example: 0.8
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.1
          mode: slider
    duration:
      name: Duration
      description: "The duration in seconds for which the sound should play."
      example: 10
      selector:
        number:
          min: 0.1
          max: 16383.0
          step: 0.1
          mode: box
          unit_of_measurement: "seconds"

set_rule_state:
  name: Set Rule State
  description: Enables or disables an automation rule defined on the Homematic IP HCU.
  fields:
    rule_id:
      name: Rule ID
      description: "The unique identifier of the rule to control."
      example: "a12c135-e54b-555a-fa45-e3054c894321"
      required: true
      selector:
        text:
    enabled:
      name: Enabled
      description: "Whether to enable or disable the rule."
      example: true
      required: true
      selector:
        boolean:
